version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/usr/src/app/public
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_management_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  xampp:
    image: cvaranasi/xampp
    ports:
      - "80:80"